<?php
// +----------------------------------------------------------------------
// | CoreThink [ Simple Efficient Excellent ]
// +----------------------------------------------------------------------
// | Copyright (c) 2014 http://www.corethink.cn All rights reserved.
// +----------------------------------------------------------------------
// | Author: ijry <ijry@qq.com> <http://www.corethink.cn>
// +----------------------------------------------------------------------
return array(
    'group'=>array(
        'title'=>'是否开启图片分组:',
        'type'=>'radio',
        'options'=>array(
            '1'=>'开启',
            '0'=>'关闭',
        ),
        'value'=>'1',
    ),
    'transitionIn'=>array(
        'title'=>'动画进入效果:',
        'type'=>'radio',
        'options'=>array(
            'elastic'=>'弹性弹出',
            'fade'=>'渐变的',
            'none'=>'没有效果',
        ),
        'value'=>'fade',
    ),
    'transitionOut'=>array(
        'title'=>'动画消失效果:',
        'type'=>'radio',
        'options'=>array(
            'elastic'=>'弹性弹出',
            'fade'=>'渐变的',
            'none'=>'没有效果',
        ),
        'value'=>'fade',
    ),
    'padding'=>array(
        'title'=>'浏览框内边距:',
        'type'=>'text',
        'value'=>'10',
    ),
    'hideOnContentClick'=>array(
        'title'=>'是否点击图片关闭:',
        'type'=>'radio',
        'options'=>array(
            'true'=>'是',
            'false'=>'否',
        ),
        'value'=>'false',
    ),
    'easingIn'=>array(
        'title'=>'为elastic设置动画属性(具体效果请查阅Easing属性效果):',
        'type'=>'select',
        'options'=>array(
            'linear'=>'linear',
            'swing'=>'swing',
            'jswing'=>'jswing',
            'easeInQuad'=>'easeInQuad',
            'easeOutQuad'=>'easeOutQuad',
            'easeInOutQuad'=>'easeInOutQuad',
            'easeInCubic'=>'easeInCubic',
            'easeOutCubic'=>'easeOutCubic',
            'easeInOutCubic'=>'easeInOutCubic',
            'easeInQuart'=>'easeInQuart',
            'easeOutQuart'=>'easeOutQuart',
            'easeInOutQuart'=>'easeInOutQuart',
            'easeInQuint'=>'easeInQuint',
            'easeOutQuint'=>'easeOutQuint',
            'easeInOutQuint'=>'easeInOutQuint',
            'easeInSine'=>'easeInSine',
            'easeOutSine'=>'easeOutSine',
            'easeInOutSine'=>'easeInOutSine',
            'easeInExpo'=>'easeInExpo',
            'easeOutExpo'=>'easeOutExpo',
            'easeInOutExpo'=>'easeInOutExpo',
            'easeInCirc'=>'easeInCirc',
            'easeOutCirc'=>'easeOutCirc',
            'easeInOutCirc'=>'easeInOutCirc',
            'easeInElastic'=>'easeInElastic',
            'easeOutElastic'=>'easeOutElastic',
            'easeInOutElastic'=>'easeInOutElastic',
            'easeInBack'=>'easeInBack',
            'easeOutBack'=>'easeOutBack',
            'easeInOutBack'=>'easeInOutBack',
            'easeInBounce'=>'easeInBounce',
            'easeOutBounce'=>'easeOutBounce',
            'easeInOutBounce'=>'easeInOutBounce'
        ),
        'value'=>'easeOutCubic',
    ),
);
